services:
  otel:
    image: jaegertracing/all-in-one:latest
    command:
      - "--collector.otlp.enabled=true"
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 4317:4317
