services:
  nginx:
    image: nginx:latest
    volumes:
      - ../config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: ../
      dockerfile: Dockerfile
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: 0.25
          memory: 64M
    expose:
      - 3000
